baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "lemonade"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/article/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight =3
